version: "3"
 
services:
  jenkins:
    user: root
    image: "jenkinsci/blueocean:1.23.1"
    ports:
      - "8081:8081"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynet
    
networks:
  mynet:
    driver: bridge